# Getting Started with NumPy
Numpy (Numerical Python) is an open source library in Python that we can use for numerical computing.

## Features
- *N-dimensional array* Is the core data structure in NumpPy
- *Vectorized operations* Perform element-wise operations without explicit loops
- *Mathematical functions* Includes tools for linear algebra, Fourier transforms, statics, etc.
- *Integration with libraries* Widely used with Pandas, SciPy, TensorFlow and scikit-learn.

In [2]:
import numpy as np

### Array Creation

Create different types of arrays using NumPy.

Tasks:

- Create a 1D array containing numbers from 10 to 20 (inclusive).
- Create a 3×3 array filled with zeros.
- Create a 4×4 identity matrix.
- Create an array of 5 random integers between 1 and 100.

In [113]:
arr1 = np.arange(10, 21)
arr2 = np.zeros((3,3))
arr3 = np.identity(4)
arr4 = np.random.randint(100, size=5)

results = [arr1, arr2, arr3, arr4]

for i in range(len(results)):
    print(f"\nExercise {i+1}")
    print(results[i])


Exercise 1
[10 11 12 13 14 15 16 17 18 19 20]

Exercise 2
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Exercise 3
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

Exercise 4
[55 65 59 18 37]


### Array Indexing and Slicing

Practice accessing and modifying elements in arrays.
Tasks:
- Given the array `a = np.array([5, 10, 15, 20, 25, 30])`,
    * Extract the first three elements.
    * Extract the last two elements.
    * Replace the middle two elements with `[0, 0]`.
- Given a 3×3 array `b = np.arange(1, 10).reshape(3, 3)`,
    * Access the element in the second row, third column.
    * Extract the first two rows.

In [177]:
a = np.array([5, 10, 15, 20, 25, 30])
print("\nPart 1")
print(f"Original array: {a}")

print(a[:3])
print(a[-2:])
size = a.size
mid1 = (size // 2 - 1)
mid2 = mid1 + 1
a[[mid1, mid2]] = [0, 0]
print(a)

print("\nPart 2")
b = np.arange(1, 10).reshape(3, 3)
print(f"Original array: \n{b}")
print(b[1][2])
print(b[:2])
print(b)
print()
print(b[:2, 2])


Part 1
Original array: [ 5 10 15 20 25 30]
[ 5 10 15]
[25 30]
[ 5 10  0  0 25 30]

Part 2
Original array: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
6
[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]

[3 6]


### Array Operations

Apply arithmetic and statistical operations.
Tasks:

```python
x = np.array([1, 2, 3, 4])
y = np.array([10, 20, 30, 40])
```

Perform:
- Element-wise addition
- Element-wise multiplication
- Compute the mean and standard deviation of `y`

In [29]:
x = np.array([1, 2, 3, 4])
y = np.array([10, 20, 30, 40])
print(x + y)
print(x * y)
print(y.mean())
print(round(y.std(), 2))

[11 22 33 44]
[ 10  40  90 160]
25.0
11.18


### Reshaping and Flattening

Work with array shapes.
Tasks:
- Create an array of numbers from 1 to 12 and reshape it into a 3×4 array.
- Reshape the same array into a 4×3 array.
- Flatten the array back into a 1D array.

In [14]:
arr = np.random.randint(20, size=12)
r = arr.reshape(3,4)
print(r)
print(f"\n{r.reshape(4,3)}")
print(f"\n{r.ravel()}")

[[14  3  9  4]
 [13 12  7  1]
 [19 14 11 18]]

[[14  3  9]
 [ 4 13 12]
 [ 7  1 19]
 [14 11 18]]

[14  3  9  4 13 12  7  1 19 14 11 18]


### Conditional Selection
Use boolean indexing.
Tasks:
- Create an array of 10 random integers between 0 and 50.
- Extract all numbers greater than 25.
- Replace all even numbers with -1.

In [28]:
arr = np.random.randint(0,51, size=10)
mask = arr > 25
print(arr[mask])
arr[arr % 2 == 0] = -1
print(arr)

[28 29 27 38 30 31 45]
[-1 29 27 -1 21 -1 21  5 31 45]
